routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('welcome', function () {
    return view('welcome');
})->name('welcome');

require __DIR__.'/web/admin.php';
require __DIR__.'/web/frontend.php';

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        $lastPoint = collaborator()->points()->latest()->first();

        return view('frontend.home')
            ->with('latestPoint', $lastPoint ? $lastPoint->created_at->format('d/m/Y H:i:s') : "Sem pontos registrados");
    }
}

app/Http/Controllers/Frontend/PointController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Services\PointService;
use Illuminate\Http\Request;

class PointController extends Controller
{
    public function point()
    {
        if((new PointService)->hitPoint()) {
            return back()->with('success', 'Tudo certo, ponto registrado com sucesso!');
        }

        return back()->with('message', 'Erro ao bater ponto');
    }
}

app/Http/Controllers/Frontend/ProfileController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    /**
     * Show the form for editing current user
     *
     * @return View
     *
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit()
    {
        $instance = collaborator();

        return view('frontend.profile.edit')->with('instance', $instance);
    }

    /**
     * Update the current user.
     *
     * @return RedirectResponse
     *
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(Request $request)
    {
        $instance = collaborator();

        $this->validate($request, [
            'email' => ['unique:users,email,'.$instance->getKey()],
            'password' => $request->input('password') ? ['required', 'min:8'] : [],
            'password-confirmation' => $request->input('password') ? ['required', 'same:password'] : [],
        ]);

        $instance->name = $request->input('name');
        $instance->email = $request->input('email');

        if($request->input('password')) {
            $instance->password = bcrypt($request->input('password'));
        }

        $instance->save();

        return back()->with(
            'success', 'Dados alterados com sucesso!'
        );
    }
}

app/View/Components/FrontendLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class FrontendLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('frontend.layouts.frontend');
    }
}

resources/views/frontend/profile/edit.blade.php
<x-frontend-layout>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <span class="text-2xl">Perfil de Usuário</span>
                </div>
            </div>
        </div>
    </div>

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <form method="POST" action="{{ route('web.frontend.update') }}">
            @csrf

            <!-- Email Address -->
            <div>
                <x-label for="name" :value="__('Nome')" />

                <x-input id="name" class="block mt-1 w-full" type="text" name="name" value="{{ $instance->name }}" required autofocus />
            </div>

            <!-- Email Address -->
            <div class="mt-4">
                <x-label for="email" :value="__('Email')" />

                <x-input id="email" class="block mt-1 w-full" type="email" name="email" value="{{ $instance->email }}" autofocus />
            </div>

            <hr class="mt-8" />

            <!-- Password -->
            <div class="mt-4">
                <x-label for="password" :value="__('Senha')" />

                <x-input id="password" class="block mt-1 w-full" type="password" name="password" autocomplete="current-password" />
            </div>

            <div class="mt-4">
                <x-label for="password-confirmation" :value="__('Confirmação de Senha')" />

                <x-input id="password-confirmation" class="block mt-1 w-full" type="password" name="password-confirmation" autocomplete="current-password" />
            </div>

            <div class="flex justify-end items-center block mt-6">
                <x-button>{{ __('Salvar') }}</x-button>
            </div>
        </form>
    </div>
</x-frontend-layout>